### ISSUE TITLE
[WAGON-369] wagon http doesn't follow HTTP 302 redirects for PUT

### ISSUE THREAD

**Issue by olamy** [olamy/maven-wagon#148]
**[James Baldassari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbaldassari)** opened **[WAGON-369](https://issues.apache.org/jira/browse/WAGON-369?redirect=false)** and commented

We have a reverse proxy server sitting in front of our Artifactory repository.  We've been running with this configuration for over a year with no problems until we upgraded to Maven 3.0.4 and maven-deploy-plugin 2.7.  When deploying an artifact to a repository, if the request returns a 302 redirect, maven-deploy-plugin 2.7 does not follow the redirect and simply fails.  It seems like a regression was introduced in maven-deploy-plugin some time after v2.5 (the default version used by Maven 3.0.3, which works).  The full stack trace follows:

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project myartifact: Failed to deploy artifacts: Could not transfer artifact mycompany:myartifact:pom:4.4.4 from/to maven01 (http://maven.mycompany.net/libs-releases-local): Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found. -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project myartifact: Failed to deploy artifacts: Could not transfer artifact mycompany:myartifact:pom:4.4.4 from/to dxmaven01 (http://maven.mycompany.net/libs-releases-local): Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found.
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
[INFO] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
[INFO] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
[INFO] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
[INFO] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:597)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to deploy artifacts: Could not transfer artifact mycompany:myartifact:pom:4.4.4 from/to dxmaven01 (http://maven.mycompany.net/libs-releases-local): Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found.
[INFO] 	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:193)
[INFO] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[INFO] 	... 19 more
[INFO] Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to deploy artifacts: Could not transfer artifact mycompany:myartifact:pom:4.4.4 from/to dxmaven01 (http://maven.mycompany.net/libs-releases-local): Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found.
[INFO] 	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:141)
[INFO] 	at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:167)
[INFO] 	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:149)
[INFO] 	... 21 more
[INFO] Caused by: org.sonatype.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact mycompany:myartifact:pom:4.4.4 from/to dxmaven01 (http://maven.mycompany.net/libs-releases-local): Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found.
[INFO] 	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:280)
[INFO] 	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:211)
[INFO] 	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:443)
[INFO] 	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:137)
[INFO] 	... 23 more
[INFO] Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact mycompany:myartifact:pom:4.4.4 from/to dxmaven01 (http://maven.mycompany.net/libs-releases-local): Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found.
[INFO] 	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
[INFO] 	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
[INFO] 	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:837)
[INFO] 	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:467)
[INFO] 	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:274)
[INFO] 	... 26 more
[INFO] Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://maven.mycompany.net/libs-releases-local/mycompany/myartifact/4.4.4/myartifact-4.4.4.pom. Return code is: 302, ReasonPhrase:Found.
[INFO] 	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:562)
[INFO] 	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:471)
[INFO] 	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:451)
[INFO] 	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:811)
[INFO] 	... 28 more
[INFO] [ERROR] 
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

---

**Affects:** 2.2

**Comment by olamy** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

My guess would be: somebody already deployed an artifact with this groupId, artifactId and version.

**Comment by olamy** [comment]
**[James Baldassari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbaldassari)** commented

This problem happens during a mvn release, so we're deploying an artifact that has just been tagged.  Therefore there shouldn't be any other artifacts with the same coordinates in the repository.  One other data point I've been able to gather since filing this bug is that we tried a deploy with Maven 3.0.4 and specifically downgraded maven-deploy-plugin to v2.5, and we still had this issue.  So it's possible that it's not maven-deploy-plugin but some other component that changed between Maven 3.0.3 and 3.0.4.  If there is any other info that might be helpful, let me know and I'll try to get it.  It's fairly easy to reproduce this problem just by attempting to tag a release with Maven 3.0.4.

**Comment by olamy** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The success of the tagging could be a false positive. There's a known issue with SVN (MRELEA[SE-719](https://issues.apache.org/jira/browse/SE-719)) when tagging doesn't break the build if the tag already exists.
So did the `mycompany:myartifact:pom:4.4.4` already exist?

**Comment by olamy** [comment]
**[James Baldassari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbaldassari)** commented

No, the artifact did not exist prior to the deploy.  The deploy was being performed as part of a release, so this version didn't exist until the mvn release was started.  After encountering this failure, if we simply switch back to Maven 3.0.3 we can deploy without issue.  The problem appears to be the 302 redirect that the reverse proxy server is returning.  It looks like some component of Maven is expecting only a 200 (or some other set of status codes that it considers valid), and when it sees the 302 it simply gives up instead of following the redirect.

**Comment by olamy** [comment]
**[James Baldassari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbaldassari)** commented

To address your question regarding MRELEA[SE-719](https://issues.apache.org/jira/browse/SE-719), the tag did not already exist either.  We encountered this deploy failure on the first attempt to tag with Maven 3.0.4.  This wasn't a one-time problem, either.  It happened every time we tried to tag a release.  We had to instruct everyone to roll back to 3.0.3 because no one could release any artifacts with 3.0.4.

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

I agree there is possible issues with redirect. I'm having a look.
BTW the http specs (http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) says "the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user".
But I agree that's crazy to implements that :-)

**Comment by olamy** [comment]
**[James Baldassari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbaldassari)** commented

That's interesting.  I guess reading the spec is never a bad idea either :)
If you want to follow the spec then the user could be prompted to hit [enter] or something to confirm that the redirect is desired/correct/secure, but whether it's automatic or user-confirmed, there should be some way to do it.

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

But as usual nobody implements specs :-) as 302 is something automatically followed by http clients whereas they shouldn't in fact :-)

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed for PUT. I will now have a look to write unit test for other http methods used (i.e. get )

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

feel free to make some tests with maven 3.0.5-SNAPSHOT available here https://builds.apache.org/view/M-R/view/Maven/job/maven-3.0.x/

Let us know if you still have issues.

**Comment by olamy** [comment]
**[James Baldassari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jbaldassari)** commented

Thanks very much!  I'll try to find some time to test it out soon.

**Comment by olamy** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

even if redirect on get worked fine I have added unit test.

**Comment by olamy** [comment]
**[Mukarram Baig](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kilokahn)** commented

I am having a strange problem in deploying artifacts to the snapshot repository fronted by Nexus as the repository manager. With version 3.0.3, I am able to deploy correctly. With version 3.0.4, I get the 302 error that is mentioned here. With version 3.0.5, I get a "Return code is: 401, ReasonPhrase: Unauthorized. " error. I triple-checked that the exact same settings.xml file is used across all three version (ruling out the possibility of incorrect username/password). Does anyone know what might be the reason behind this? I am pretty sure that I am missing out something elementary. Thanks!

**Comment by olamy** [comment]
**[Bruno Medeiros](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brunojcm)** commented

Mukarram, I have a very similar problem, but I get the wrong "Unauthorized" problem when following redirects with any maven above 3.0.4, even 3.1.1 a 3.2.3.

I've just created a new issue for that: https://jira.codehaus.org/browse/WAGON-421
