### ISSUE TITLE
[WAGON-461] URL string not properly encoded by webdav

### ISSUE THREAD

**Issue by olamy** [olamy/maven-wagon#216]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** opened **[WAGON-461](https://issues.apache.org/jira/browse/WAGON-461?redirect=false)** and commented

wagon-webdav is not calling EncodingUtil prior to instantiating MkColMethod which results in

```java
Caused by: java.lang.IllegalArgumentException: Invalid uri 'https://snafu.sharefile-webdav.com/Shared Folders/Fit - Expert Services/IBM/': escaped absolute path not valid
```

when there are special characters in the URI string.

Changing line 153 of org.apache.maven.wagon.providers.webdav.WebDavWagon from

```java
method = new MkColMethod( url );
```

to

```java
method = new MkColMethod( EncodingUtil.encodeURLToString( url ) );
```

solves the issue although you may want to fix it elsewhere in the flow.

---

**Affects:** 2.10

**Attachments:**
- [logs.zip](https://issues.apache.org/jira/secure/attachment/12823980/logs.zip) (_7.06 kB_)

**Issue Links:**
- [WAGON-488](https://issues.apache.org/jira/browse/WAGON-488) Upgrade WebDAV Wagon to a more recent HttpClient version (4.5.3)
 (_**"depends upon"**_)

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Where does the URI come from, especially the path (`/Shared Folders/Fit - Expert Services/IBM`)? It pretty much looks like invalid input from the POM.

**Comment by olamy** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

It's from Sharefile and it is a valid Sharefile webdav URI. Adding the encodeURLToString results in a successful file transfer into the target Sharefile folder. I can send you a Pull request with my working change if you like.

Putting debug statements into WebDavWagon shows that the problem is the code is not URL encoding the spaces which then causes HttpMethodBase to blow-up.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I have no idead what Sharefile but I am trying to figure out **who** is actually providing this faulty URI. What makes you think that this is a valid URI?

**Comment by olamy** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

I apologize, I misunderstood your earlier question.

The webdav string comes from a pom:

```xml
<plugin>
   <groupId>org.codehaus.mojo</groupId>
   <artifactId>wagon-maven-plugin</artifactId>
   <version>1.0</version>
   <executions>
      <execution>
         <id>upload-assembly</id>
         <phase>install</phase>
         <goals>
            <goal>upload-single</goal>
         </goals>
         <configuration>
            <serverId>sharefile-ftp</serverId>
            <fromFile>${project.build.directory}/${project.build.finalName}.jar</fromFile>
            <!--
               <url>ftp://snafu.sharefileftp.com/FIT - Expert Services/IBM/</url>
            -->
            <url>dav:https://snafu.sharefile-webdav.com/Shared Folders/Fit - Expert Services/IBM</url>
         </configuration>
      </execution>
   </executions>
</plugin>
```

It _is_ a valid webdav URI, it is simply not encoded properly by wagon-webdav. Adding the one line of code to encode the URI fixes the problem. Hand encoding the URI in the POM does not fix the problem.

Using wagon-ftp rather than wagon-webdav also works

```xml
<url>ftp://snafu.sharefileftp.com/FIT - Expert Services/IBM/</url>
```

which seems to indicate the the encoding is not a plugin function.

_Is_ it the plugins job to encode the URI?

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This is actually what I wanted to see. The URI ist not valid, see [here](http://stackoverflow.com/a/497972/696632) for a citation of the appropriate RFC.

**Comment by olamy** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

Right, I tried that originally however pre-encoding the URI in the pom doesn't help as the URI is finally encoded farther down the code chain which then encodes the encoding.

pom.xml

```xml
<url>dav:https://snafu.sharefile-webdav.com/Shared%20Folders/Fit%20-%20Expert%20Services/IBM</url>
```

Stack trace:

```java
[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:upload-single (upload-assembly) on project synthetics-monitor-plugin: Error handling resource: Failed to transfer file: https://snafu.sharefile-webdav.com/Shared%2520Folders/Fit%2520-%2520Expert%2520Services/IBM/synthetics-monitor-plugin-1.0.0.jar. Return code is: 409 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:upload-single (upload-assembly) on project synthetics-monitor-plugin: Error handling resource
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error handling resource
	at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingleWagonMojo.java:68)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
```

Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://snafu.sharefile-webdav.com/Shared%2520Folders/Fit%2520-%2520Expert%2520Services/IBM/synthetics-monitor-plugin-1.0.0.jar. Return code is: 409

```java
at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:417)
at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:324)
at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:301)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.put(WebDavWagon.java:326)
at org.codehaus.mojo.wagon.UploadSingleMojo.execute(UploadSingleMojo.java:70)
at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingleWagonMojo.java:64)
... 22 more
```

wagon-ftp working on the unencoded pom URI is also an indication that pre-encoding the URI in the pom is probably not the right direction. I would think that both wagon-ftp and wagon-webdav would have the same interface contract with the plugin, but perhaps not.

Also, pre-encoding the URI doesn't make a lot of sense given that adding the encoding call to WebDavWagon does work.

If you have an alternate URI encoding you're thinking of please forward it and I'll give it a try.

Thanks.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks for the input. 409:

> The request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request.

This error does not seem to relate to the URI but to another issue. Can you also provide a full debug log?
As far ar I know, the client must create the collection `.../IBM` first before perform the `PUT` operation. Can you create provide a minimal project with does this DAV upload? I will retry with the Apache DAV module. Additionally, do the collections upto IBM exist on the server already?

**Comment by olamy** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

The 409 is a result of the malformed URI. The exception message shows the encoded URI with escaped spaces has been further escaped- the space (%20) has been escaped to %2520 which is incorrect.

https://snafu.sharefile-webdav.com/Shared%2520Folders/Fit%2520-%2520Expert%2520Services/IBM/synthetics-monitor-plugin-1.0.0.jar.

The collection exists. wagon-webdav works _if_ WebDavWagon provides the encoding as required by org.apache.common.httpclient.HttpMethodBase(String uri)

```java
/**
* Constructor specifying a URI.
* It is responsibility of the caller to ensure that URI elements
* (path & query parameters) are properly encoded (URL safe).
```

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Just checked the code. Something seems to be fishy about Jackrabbit here since HttpClient does require the URI to be encoded which you did first. Someone applies `encodeURI` a second time. Have you enabled debugging on Jackrabbit and HttpClient? You should see where the encoding happens again.

**Comment by olamy** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

I did, debug didn't reveal anything- there's not much logging in Jackrabbit.

I added some debug logging to my local copy of the source and it shows that the URI is not encoded at the point that it instantiates MkColMethod which leads directly to the HttpClient problem.

The double encoding is a puzzle. Why adding the encode on the call to MkColMethod doesn't break is also odd.

As soon as I can I'll add two tests to the test suite, 1) URI with spaces, and 2) URI with encoded spaces- that should help with the puzzle.

Thanks for your help.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please read [this](https://hc.apache.org/httpcomponents-client-ga/logging.html). It will guide you how to enable logging on the HttpClient. We can tackle the issue down here. The quirk must be somewhere.

**Comment by olamy** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

Log files for both encoded (in pom) and unencoded URLs.

log settings:

```java
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=true
org.slf4j.simpleLogger.logFile=System.out
org.slf4j.simpleLogger.levelInBrackets=true
org.slf4j.simpleLogger.log.Sisu=debug
org.slf4j.simpleLogger.warnLevelString=WARNING

org.slf4j.simpleLogger.log.org.apache.http=trace
org.slf4j.simpleLogger.log.org.apache.http.wire=error
org.slf4j.simpleLogger.log.org.apache.commons.httpclient=trace
org.slf4j.simpleLogger.log.org.apache.commons.httpclient.wire=error

org.slf4j.simpleLogger.log.org.apache.jackrabbit=trace
org.slf4j.simpleLogger.log.org.apache.maven.wagon=trace
```

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks for the log files. They help a lot. The first thing I see is that `Jakarta Commons-HttpClient/3.1` is used. If you take a closer look at the [dependencies list](http://www.mojohaus.org/wagon-maven-plugin/dependencies.html#Project_Transitive_Dependencies_runtime) of the plugin, you see that all dependencies are horribly old. Wagon is now at 2.10, Jackrabbit at 2.2.

Before doing any further analysis, one needs to upgrade Maven Wagon first.

Clone from the plugin's Git repo and try to upgrade Wagon manually and test. Open an issue for upgrading it. Hopefully, there aren't any interface/ABI changes.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No reaction for almost two years...
