### ISSUE TITLE
[WAGON-492] Using Wagon component with Spring

### ISSUE THREAD

**Issue by olamy** [olamy/maven-wagon#226]
**[Laurent Granié](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgranie)** opened **[WAGON-492](https://issues.apache.org/jira/browse/WAGON-492?redirect=false)** and commented

I'm using Wagon with Spring.
With version 2.10 it's ok. But since version 2.12 I can not load component into Spring.
You can find my DownloaderServiceBean attached.

The error is like :
Unsatisfied dependency expressed through field 'downloader': Error
creating bean with name 'downloaderBean': Invocation of init method
failed; nested exception is java.lang.NoSuchMethodError:
org.codehaus.plexus.configuration.PlexusConfiguration.setName(Ljava/lang/String;)V;
nested exception is
org.springframework.beans.factory.BeanCreationException: Error
creating bean with name 'downloaderBean': Invocation of init method
failed; nested exception is java.lang.NoSuchMethodError:
org.codehaus.plexus.configuration.PlexusConfiguration.setName(Ljava/lang/String;)V

---

**Affects:** 2.12

**Attachments:**
- [bniapi-wagon.zip](https://issues.apache.org/jira/secure/attachment/12901696/bniapi-wagon.zip) (_14.23 kB_)
- [DownloaderBean.java](https://issues.apache.org/jira/secure/attachment/12899578/DownloaderBean.java) (_16.75 kB_)

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Can you provide a sample project, XML beans or Java beans?

**Comment by olamy** [comment]
**[Laurent Granié](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgranie)** commented

Is DownloaderBean.java in the Attachments part enough?

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No, I need a complete sample project. This is some kind of dep/version mismatch.

**Comment by olamy** [comment]
**[Laurent Granié](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgranie)** commented

Exemple project

**Comment by olamy** [comment]
**[Laurent Granié](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgranie)** commented

I attached a project.
When I execute test, I've got no problem.
But when I use it in JBoss 6.4, here what is :
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'downloaderBean': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.codehaus.plexus.configuration.PlexusConfiguration.setName(Ljava/lang/String;)V
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:187) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1213) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1053) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1018) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
... 112 more
Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.configuration.PlexusConfiguration.setName(Ljava/lang/String;)V
at org.codehaus.plexus.configuration.DefaultPlexusConfiguration.addChild(DefaultPlexusConfiguration.java:222) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.configuration.DefaultPlexusConfiguration.getChild(DefaultPlexusConfiguration.java:165) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.configuration.DefaultPlexusConfiguration.getChild(DefaultPlexusConfiguration.java:149) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.container.initialization.InitializeComponentRegistryPhase.getComponentRepository(InitializeComponentRegistryPhase.java:65) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.container.initialization.InitializeComponentRegistryPhase.execute(InitializeComponentRegistryPhase.java:40) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.DefaultPlexusContainer.initializePhases(DefaultPlexusContainer.java:644) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.DefaultPlexusContainer.initialize(DefaultPlexusContainer.java:556) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.DefaultPlexusContainer.construct(DefaultPlexusContainer.java:281) [plexus-container-default-1.7.1.jar:]
at org.codehaus.plexus.DefaultPlexusContainer.\<init>(DefaultPlexusContainer.java:172) [plexus-container-default-1.7.1.jar:]
at com.rtd.bni.wagon.DownloaderBean.initialize(DownloaderBean.java:92) [bniapi-wagon-1.0-SNAPSHOT.jar:]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_91]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_91]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_91]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_91]
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:310) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) [spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
... 125 more

**Comment by olamy** [comment]
**[Laurent Granié](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgranie)** commented

If I use this DownloaderBean with SpringBoot 1.5.9-RELEASE it's ok.
So finally, it's not really a wagon bug.
It's maybe more a dependency problem due to JBoss 6.4 modules/sub-system dependencies.

**Comment by olamy** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

JBoss has its own module system with CL isolation. Can this be closed as invalid?

**Comment by olamy** [comment]
**[Laurent Granié](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lgranie)** commented

I manage to determine the problem.

There is a dependency in wagon-ssh to plexus-interactivity-api which depends on plexus-component-api who declare another PlexusConfiguration interface than the one I'm using in plexus-container-default.

Solution is :
\<dependency>
\<groupId>org.apache.maven.wagon\</groupId>
\<artifactId>wagon-ssh\</artifactId>
\<version>${wagon.version}\</version>
\<exclusions>
\<exclusion>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-component-api\</artifactId>
\</exclusion>
\</exclusions>
\</dependency>
