### ISSUE TITLE
[WAGON-206] NullPointerException in jsch ChannelSession when deploying

### ISSUE THREAD

**Issue by olamy** [olamy/maven-wagon#293]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[WAGON-206](https://issues.apache.org/jira/browse/WAGON-206?redirect=false)** and commented

While deploying maven-surefire-plugin for instance
I don't know if it really affects the deploy or not, everything looks fine

[INFO] [deploy:deploy]
[INFO] Retrieving previous build number from apache.snapshots
[DEBUG] adding permissions to wagon connection: 664 775
Uploading: scp://minotaur.apache.org/www/cvs.apache.org/maven-snapshot-repository/org/apache/maven/plugins/maven-surefire-plugin/2.3-SNAPSHOT/maven-surefire-plugin-2.3-20060701.160450-2.jar
12K uploaded
Exception in thread "Exec thread minotaur.apache.org" java.lang.NullPointerException
at com.jcraft.jsch.ChannelSession.run(Unknown Source)
at java.lang.Thread.run(Thread.java:619)
[INFO] Retrieving previous metadata from apache.snapshots
[DEBUG] project information for maven-surefire-plugin 2.3-20060701.160450-2 could not be found on repository: apache.snapshots
[INFO] Uploading project information for maven-surefire-plugin 2.3-20060701.160450-2
[DEBUG] adding permissions to wagon connection: 664 775

---

**Affects:** 1.0-alpha-7

2 votes, 3 watchers

**Comment by olamy** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Using maven 2.0.4

**Comment by olamy** [comment]
**[Fabrizio Giustina](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fgiust)** commented

Under java 6 on windows I have this same error at each deploy.
Looks like a problem in jsch 1.0.27 and I can confirm that it's fixed by upgrading to 1.0.31. By simply replacing the jsch jar in maven libs (maven 2.0.5) this error goes away.
Wagon dependency should be upgraded to 1.0.31 asap...

**Comment by olamy** [comment]
**[Geert Jan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=geertjan)** commented

Same goes for maven 1.1-beta-3

**Comment by olamy** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Upgraded jsch to 0.1.31
