### ISSUE TITLE
[WAGON-131] NPE in wagon-ftp

### ISSUE THREAD

**Issue by olamy** [olamy/maven-wagon#66]
**[Jean-Laurent de Morlhon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeanlaurent)** opened **[WAGON-131](https://issues.apache.org/jira/browse/WAGON-131?redirect=false)** and commented

When deploying a pom project to an ftp repository there is an NPE see trace below.
Don't know if it's related but there is no binary ftp client on the machine.

Issuing the same command on a windows machine deploys succesfully.

[INFO] [deploy:deploy]
[INFO] Retrieving previous build number from tux3-ftp-repository
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] null
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection(FtpWagon.java:127)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:354)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:295)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:356)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:310)
at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLatestSnapshotBuildNumber(SnapshotTransformation.java:158)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:97)
at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForDeployment(DefaultArtifactTransformationManager.java:61)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:68)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:131)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 1 minute 5 seconds
[INFO] Finished at: Fri Feb 17 17:26:57 CET 2006
[INFO] Final Memory: 6M/25M
[INFO] ------------------------------------------------------------------------

---

**Issue Links:**
- [WAGON-132](https://issues.apache.org/jira/browse/WAGON-132) Null-Pointer Exception when password tag missing or empty in maven2 settings.xml
 (_**"is duplicated by"**_)
- [WAGON-63](https://issues.apache.org/jira/browse/WAGON-63) NPE using ftp-wagon if ~/.m2/settings.xml is missing
 (_**"is duplicated by"**_)

1 votes, 0 watchers

**Comment by olamy** [comment]
**[Jean-Laurent de Morlhon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeanlaurent)** commented

above NPE is related to a missing credential for the ftp server in settings.xml.
adding

\<servers>
\<server>
\<id>tux3-ftp-repository\</id>
\<username>username\</username>
\<password>password\</password>
\</server>
\</servers>

solves the problem.

Anyway, rather than an NPE we could have a more precise error message :)

**Comment by olamy** [comment]
**[Abel Cuenca](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abel_cuenca)** commented

I have a similar problem, although I'm not using maven 2.x but maven tasks for ant.

This is my configuration. In my ${HOME}/.m2/ there is a settings.xml file with a servers section with these lines:
...
\<server>
\<id>cmebdes\</id>
\<username>A134209\</username>
\<password>kk\</password>
\</server>
...

and then, in my build.xml I have these lines:

    <artifact:install-provider artifactId="wagon-ftp" version="1.0-alpha-6"/>
    <artifact:remoteRepository id="cmebdes" url="ftp://10.14.10.190/aplicaciones/iplanet/docroot/_econew/repositorio/maven2"/>
    
    <target name="deploy" depends="jar">
        <artifact:deploy file="${jar.path}/${jar.name}">
            <remoteRepository refid="cmebdes" />
        <pom refid="maven.project"/>
        </artifact:deploy>
    </target>

Of course, FTP connection works manually, but when I execute 'ant -d deploy' I get the following error:
...
[artifact:deploy] Deploying to ftp://10.14.10.190/aplicaciones/iplanet/docroot/_econew/repositorio/m
aven2

BUILD FAILED
C:\Documents and Settings\a134209\proyectos\desarrolloeCo\build.xml:1559: java.lang.NullPointerException
at org.apache.tools.ant.Task.perform(Task.java:373)
at org.apache.tools.ant.Target.execute(Target.java:341)
at org.apache.tools.ant.Target.performTasks(Target.java:369)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1216)
at org.apache.tools.ant.Project.executeTarget(Project.java:1185)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:40)
at org.apache.tools.ant.Project.executeTargets(Project.java:1068)
at org.apache.tools.ant.Main.runBuild(Main.java:668)
at org.apache.tools.ant.Main.startAnt(Main.java:187)
at org.apache.tools.ant.launch.Launcher.run(Launcher.java:246)
at org.apache.tools.ant.launch.Launcher.main(Launcher.java:67)
Caused by: java.lang.NullPointerException
at org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection(FtpWagon.java:127)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:178)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:109)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:77)
at org.apache.maven.artifact.ant.DeployTask.doExecute(DeployTask.java:112)
at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:451)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
at org.apache.tools.ant.Task.perform(Task.java:364)
... 10 more
--- Nested Exception ---
...

What I'm doing wrong?

TIA,
Abel.

**Comment by olamy** [comment]
**[Oliver Fink](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olifink)** commented

Actually after a lot of playing around, I've found out the following (for the maven anttasks)

* settings.xml seem to be happily ignored
* ftp only works if authentication is declared with the remote repository **inside** the `artifact:deploy` task. If it is declared outside and referenced by a `refid` authentication won't work

**Comment by olamy** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

i think this was already fixed in later versions, like 1.0-beta-2
